const playingCards = [
     {
          name: 'Two of Clubs',
          value: 2,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '2',
     },
     {
          name: 'Three of Clubs',
          value: 3,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '3',
     },
     {
          name: 'Four of Clubs',
          value: 4,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '4',
     },
     {
          name: 'Five of Clubs',
          value: 5,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '5',
     },
     {
          name: 'Six of Clubs',
          value: 6,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '6',
     },
     {
          name: 'Seven of Clubs',
          value: 7,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '7',
     },
     {
          name: 'Eight of Clubs',
          value: 8,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '8',
     },
     {
          name: 'Nine of Clubs',
          value: 9,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '9',
     },
     {
          name: 'Ten of Clubs',
          value: 10,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: '10',
     },
     {
          name: 'Jack of Clubs',
          value: 11,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: 'J',
     },
     {
          name: 'Queen of Clubs',
          value: 12,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: 'Q',
     },
     {
          name: 'King of Clubs',
          value: 13,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: 'K',
     },
     {
          name: 'Ace of Clubs',
          value: 14,
          suitValue: 1,
          displayOrder: 2,
          suit: 'Clubs',
          symbol: '♣️',
          abbr: 'A',
     },
     {
          name: 'Two of Diamonds',
          value: 2,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '2',
     },
     {
          name: 'Three of Diamonds',
          value: 3,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '3',
     },
     {
          name: 'Four of Diamonds',
          value: 4,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '4',
     },
     {
          name: 'Five of Diamonds',
          value: 5,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '5',
     },
     {
          name: 'Six of Diamonds',
          value: 6,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '6',
     },
     {
          name: 'Seven of Diamonds',
          value: 7,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '7',
     },
     {
          name: 'Eight of Diamonds',
          value: 8,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '8',
     },
     {
          name: 'Nine of Diamonds',
          value: 9,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '9',
     },
     {
          name: 'Ten of Diamonds',
          value: 10,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: '10',
     },
     {
          name: 'Jack of Diamonds',
          value: 11,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: 'J',
     },
     {
          name: 'Queen of Diamonds',
          value: 12,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: 'Q',
     },
     {
          name: 'King of Diamonds',
          value: 13,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: 'K',
     },
     {
          name: 'Ace of Diamonds',
          value: 14,
          suitValue: 2,
          displayOrder: 1,
          suit: 'Diamonds',
          symbol: '♦️',
          abbr: 'A',
     },
     {
          name: 'Two of Hearts',
          value: 2,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '2',
     },
     {
          name: 'Three of Hearts',
          value: 3,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '3',
     },
     {
          name: 'Four of Hearts',
          value: 4,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '4',
     },
     {
          name: 'Five of Hearts',
          value: 5,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '5',
     },
     {
          name: 'Six of Hearts',
          value: 6,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '6',
     },
     {
          name: 'Seven of Hearts',
          value: 7,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '7',
     },
     {
          name: 'Eight of Hearts',
          value: 8,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '8',
     },
     {
          name: 'Nine of Hearts',
          value: 9,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '9',
     },
     {
          name: 'Ten of Hearts',
          value: 10,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: '10',
     },
     {
          name: 'Jack of Hearts',
          value: 11,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: 'J',
     },
     {
          name: 'Queen of Hearts',
          value: 12,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: 'Q',
     },
     {
          name: 'King of Hearts',
          value: 13,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: 'K',
     },
     {
          name: 'Ace of Hearts',
          value: 14,
          suitValue: 3,
          displayOrder: 3,
          suit: 'Hearts',
          symbol: '♥️',
          abbr: 'A',
     },
     {
          name: 'Two of Spades',
          value: 2,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '2',
     },
     {
          name: 'Three of Spades',
          value: 3,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '3',
     },
     {
          name: 'Four of Spades',
          value: 4,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '4',
     },
     {
          name: 'Five of Spades',
          value: 5,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '5',
     },
     {
          name: 'Six of Spades',
          value: 6,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '6',
     },
     {
          name: 'Seven of Spades',
          value: 7,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '7',
     },
     {
          name: 'Eight of Spades',
          value: 8,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '8',
     },
     {
          name: 'Nine of Spades',
          value: 9,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '9',
     },
     {
          name: 'Ten of Spades',
          value: 10,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: '10',
     },
     {
          name: 'Jack of Spades',
          value: 11,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: 'J',
     },
     {
          name: 'Queen of Spades',
          value: 12,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: 'Q',
     },
     {
          name: 'King of Spades',
          value: 13,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: 'K',
     },
     {
          name: 'Ace of Spades',
          value: 14,
          suitValue: 4,
          displayOrder: 4,
          suit: 'Spades',
          symbol: '♠️',
          abbr: 'A',
     },
];

export default playingCards;
